# Copyright 2023 Flavien Solt, ETH Zurich.
# Licensed under the General Public License, Version 3.0, see LICENSE for details.
# SPDX-License-Identifier: GPL-3.0-only

# This utility defines which workaround should be disabled.
# This allows, for example, to measure time to bug detection.
# Some bugs must be reintroduced in hw and cannot simply be reintroduced as a non-workaround in the fuzzer.

###
# BOOM
###

TOLERATE_BOOM_MINSTRET = False

if TOLERATE_BOOM_MINSTRET:
    print('WARNING: Tolerating one bug: TOLERATE_BOOM_MINSTRET')

###
# Rocket
###

TOLERATE_ROCKET_MINSTRET = False

if TOLERATE_ROCKET_MINSTRET:
    print('WARNING: Tolerating one bug: TOLERATE_ROCKET_MINSTRET')

###
# CVA6
###

TOLERATE_CVA6_FMULD_RDN = False

if TOLERATE_CVA6_FMULD_RDN:
    print('WARNING: Tolerating one bug: TOLERATE_CVA6_FMULD_RDN')

TOLERATE_CVA6_FDIVS_FLAGS = False

if TOLERATE_CVA6_FDIVS_FLAGS:
    print('WARNING: Tolerating one bug: TOLERATE_CVA6_FDIVS_FLAGS')

TOLERATE_CVA6_MHPMCOUNTER = False

if TOLERATE_CVA6_MHPMCOUNTER:
    print('WARNING: Tolerating one bug: TOLERATE_CVA6_MHPMCOUNTER')

TOLERATE_CVA6_MHPMEVENT31 = False

if TOLERATE_CVA6_MHPMEVENT31:
    print('WARNING: Tolerating one bug: TOLERATE_CVA6_MHPMEVENT31')


###
# Kronos
###

TOLERATE_KRONOS_READBADCSR = False

if TOLERATE_KRONOS_READBADCSR:
    print('WARNING: Tolerating one bug: TOLERATE_KRONOS_READBADCSR')

TOLERATE_KRONOS_MINSTRET = False

if TOLERATE_KRONOS_MINSTRET:
    print('WARNING: Tolerating one bug: TOLERATE_KRONOS_MINSTRET')

TOLERATE_KRONOS_FENCE = False

if TOLERATE_KRONOS_FENCE:
    print('WARNING: Tolerating one bug: TOLERATE_KRONOS_FENCE')


###
# Picorv32
###

TOLERATE_PICORV32_READNONIMPLCSR = False

if TOLERATE_PICORV32_READNONIMPLCSR:
    print('WARNING: Tolerating one bug: TOLERATE_PICORV32_READNONIMPLCSR')

TOLERATE_PICORV32_MISSINGMANDATORYCSRS = False

if TOLERATE_PICORV32_MISSINGMANDATORYCSRS:
    print('WARNING: Tolerating one bug: TOLERATE_PICORV32_MISSINGMANDATORYCSRS')

TOLERATE_PICORV32_FENCE = False

if TOLERATE_PICORV32_FENCE:
    print('WARNING: Tolerating one bug: TOLERATE_PICORV32_FENCE')

TOLERATE_PICORV32_WRITEHPM = False

if TOLERATE_PICORV32_WRITEHPM:
    print('WARNING: Tolerating one bug: TOLERATE_PICORV32_WRITEHPM')

###
# VexRiscv
###

# This prevents detecting the other bugs when using the pre-fpu-fix Vexriscv version.
FORBID_VEXRISCV_CSRS = False
if FORBID_VEXRISCV_CSRS:
    print('WARNING: Forbidding one bug: FORBID_VEXRISCV_CSRS')



TOLERATE_VEXRISCV_MINSTRET = False

if TOLERATE_VEXRISCV_MINSTRET:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_MINSTRET')

TOLERATE_VEXRISCV_IMPRECISE_FCVT = False

if TOLERATE_VEXRISCV_IMPRECISE_FCVT:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_IMPRECISE_FCVT')

TOLERATE_VEXRISCV_FMIN = False

if TOLERATE_VEXRISCV_FMIN:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_FMIN')

TOLERATE_VEXRISCV_DOUBLE_TO_FLOAT = False

if TOLERATE_VEXRISCV_DOUBLE_TO_FLOAT:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_DOUBLE_TO_FLOAT')

TOLERATE_VEXRISCV_DEPENDENT_SINGLE_PRECISION = False

if TOLERATE_VEXRISCV_DEPENDENT_SINGLE_PRECISION:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_DEPENDENT_SINGLE_PRECISION')

TOLERATE_VEXRISCV_DEPENDENT_FLE_FEQ_RET1 = False

if TOLERATE_VEXRISCV_DEPENDENT_FLE_FEQ_RET1:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_DEPENDENT_FLE_FEQ_RET1')

TOLERATE_VEXRISCV_DEPENDENT_FLT_RET0 = False

if TOLERATE_VEXRISCV_DEPENDENT_FLT_RET0:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_DEPENDENT_FLT_RET0')

TOLERATE_VEXRISCV_SQRT = False

if TOLERATE_VEXRISCV_SQRT:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_SQRT')

TOLERATE_VEXRISCV_MULDIV_CONVERSION = False

if TOLERATE_VEXRISCV_MULDIV_CONVERSION:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_MULDIV_CONVERSION')

TOLERATE_VEXRISCV_FPU_DISABLED = False

if TOLERATE_VEXRISCV_FPU_DISABLED:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_FPU_DISABLED')

TOLERATE_VEXRISCV_FPU_LEAK = False

if TOLERATE_VEXRISCV_FPU_LEAK:
    print('WARNING: Tolerating one bug: TOLERATE_VEXRISCV_FPU_LEAK')
