from params.env_helperfuncs import get_env_int, get_env_bool
from params.reduceparams_default import *
NOPIZE_SANDWICH_INSTRUCTIONS = get_env_bool("NOPIZE_SANDWICH_INSTRUCTIONS",NOPIZE_SANDWICH_INSTRUCTIONS_DEFAULT)
FLATTEN_SANDWICH_INSTRUCTIONS = get_env_bool("FLATTEN_SANDWICH_INSTRUCTIONS",FLATTEN_SANDWICH_INSTRUCTIONS_DEFAULT)
assert not FLATTEN_SANDWICH_INSTRUCTIONS, "Not implemented yet, likely not useful."
REDUCE_TAINT = get_env_bool("REDUCE_TAINT",REDUCE_TAINT_DEFAULT)
REDUCE_DEAD_CODE = get_env_bool("REDUCE_DEAD_CODE",REDUCE_DEAD_CODE_DEFAULT)
FIND_PILLARS = get_env_bool("FIND_PILLARS",FIND_PILLARS_DEFAULT)
DOUBLECHECK_MODELSIM = get_env_bool("DOUBLECHECK_MODELSIM",DOUBLECHECK_MODELSIM_DEFAULT)