NOPIZE_SANDWICH_INSTRUCTIONS_DEFAULT = True
FLATTEN_SANDWICH_INSTRUCTIONS_DEFAULT = False
REDUCE_TAINT_DEFAULT = False
REDUCE_DEAD_CODE_DEFAULT = False
FIND_PILLARS_DEFAULT = True
FIND_PILLAR_INSTRUCTION_DEFAULT = False
DOUBLECHECK_MODELSIM_DEFAULT = True
REMOVE_DEAD_INSTRUCTIONS_DEFAULT = True